### PR TITLE
CrossCollectionSearchTest: Don't pass `null` as JSON payload

### PR DESCRIPTION
**Pull request by tshak**
The test was throwing the following exception:

```
java.lang.NullPointerException: properties

	at io.orchestrate.client.RelationshipResource.put(RelationshipResource.java:314)
```

### CODE REVIEW

**Comment by dreverri** [comment]
Looks like another `@NonNull` annotation issue.

**Comment by dreverri** [comment]
We should remove the `@NonNull` annotation since we support null values.

**Comment by benjismith** [comment]
Aha. I see the problem... I think the original idea was that you'd use the method from [line 281](https://github.com/orchestrate-io/orchestrate-java-client/blob/8930329282546d7eaa9cb4643a8c4c1d37559175/src/main/java/io/orchestrate/client/RelationshipResource.java#L281)...

`public OrchestrateRequest<Boolean> put(final String relation)`

...which creates a relationship using a null JSON body. But if you wanted a JSON body, you'd use the method on [line 314](https://github.com/orchestrate-io/orchestrate-java-client/blob/8930329282546d7eaa9cb4643a8c4c1d37559175/src/main/java/io/orchestrate/client/RelationshipResource.java#L314) and it would enforce non-null-ness.

`public OrchestrateRequest<RelationshipMetadata> put(final String relation, final Object properties)`

The test is using the wrong method, which I think should indicate that our users would probably use the wrong method too pretty often...

**Comment by tshak** [comment]
Yeah - the test is using the wrong method because the test is treating `properties` as optional. I don't know the code well enough to understand the downside of allowing `null` for `properties`, but if there's no downside it's nice because it doesn't require the consumer to dispatch between two overloads at runtime.

**Comment by benjismith** [comment]
There's no downside to allowing null for properties. We should allow it.

I was just trying to remember why we added a new method, rather than just modifying the existing one, and then I remembered we didn't want to break backward compatibility. The original method was the one without a `properties` argument, and we didn't want to break existing code by adding the argument. So I added the new method and included the `@NonNull` annotation to make it clear why the two different methods existed. But in hindsight, that was a bad decision...

**Comment by benjismith** [comment]
:+1:

**Pull request merged**
