### PR TITLE
prev/next support for search queries.

### PR DESCRIPTION
**Pull request by housejester**

### CODE REVIEW

**Comment by benjismith** [comment]
When I run `gradle clean build`, I get some javadoc validation errors:

```
src/main/java/io/orchestrate/client/KvObject.java:88: error: unexpected end tag: </p>
src/main/java/io/orchestrate/client/KvObject.java:89: error: tag not allowed here: <p>
src/main/java/io/orchestrate/client/KvObject.java:84: error: element not closed: pre
```

Obviously, this is a pre-existing error. I've fixed them in the [brs-graph-properties](https://github.com/orchestrate-io/orchestrate-java-client/tree/brs-graph-properties) branch, but I'm not sure why they haven't caused a problem on circle-ci or in your environment...

**Comment by benjismith** [comment]
If I fix the javadoc validation, I can successfully build the library, but I get integration test failures.

Most of the tests in the `RelationTest` are currently failing, because the `PUT` returns a 201 now instead of a 204. That should be fine... since my java-client PR fixes those tests.

However, there's also an assertion failure in `KvListTest.getListAndPaginate`, on [line 124](https://github.com/orchestrate-io/orchestrate-java-client/blob/jde-query-next/src/integTest/java/io/orchestrate/client/itest/KvListTest.java#L124)

```
assertFalse(kvList1.getNext().hasSent());
```

**Comment by housejester** [comment]
That test failure is a bug :(  I missed a small piece in a refactoring. Yay tests!  I must have never had a clean run locally after the refactoring. Fixing.

**Comment by benjismith** [comment]
:+1:

**Comment by benjismith** [comment]
Oops. It's missing the last commit from the [brs-graph-properties](https://github.com/orchestrate-io/orchestrate-java-client/commits/brs-graph-properties) branch... I'll fix it.

**Comment by benjismith** [comment]
Okay, all good now :+1:

**Pull request merged**
